title: PyChaste

scalaversion: "3.4.0"
devscalaversion: ""

baseurl: "https://jmsgrogan.github.io/PyChaste"
markdown: Redcarpet
highlighter: rouge
exclude: [bundle-vendor]
future: true
keep_files: [documentation/python-api]
